name: ibsg
channels:
  - conda-forge
dependencies:
  - hydra
  - matplotlib=3.5
  - pandas
  - tqdm
  - black
  - plotnine
  - pip
  - pip:
    - hydra-core  
  - pyyaml
  - numpy
  - pytorch
  - pygmo
  - pathos
# and altk, installed via git for now
