name: ibsg
channels:
  - conda-forge
dependencies:
  - hydra
  - matplotlib=3.5
  - pandas
  - tqdm
  - black
  - plotnine
  - pip
  - pip:
    - hydra-core  
    - mizani==0.9.2 # There is a plotnine/numpy/mizani conflict! See https://github.com/holzschu/Carnets/issues/310
  - pyyaml
  - numpy
  - pytorch
  - pygmo
  - pathos
# and altk, installed via git for now
