universe: 100
prior: 0
num_signals: 100
distance: squared_dist
discriminative_need_gamma: 1.0
meaning_dist_gamma: 0
ib_bound_function: embo
overwrite_curves: false
maxbeta: 5
minbeta: -2
numbeta: 1500
num_processes: 6
