# MAIN (ROOT) CONFIG FILE
defaults:
  - game: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  

seed: 42

# Paths of files used for consuming and producing data
filepaths: 

  # Curves
  curve_points_save_fn: curve_points.csv # (I[M:W], I[W:U], E[D_KL[M || M']])
  mse_curve_points_save_fn: mse_curve_points.csv # (I[M:W], E[(u - u)^2])
  optimal_encoders_save_fn: optimal_encoders.pt # the encoders P(W|M) from IB method
  betas_save_fn: betas.pt # the actual beta values used in IB method

  # Simulation
  # all fns below are for saving results from all runs
  simulation_points_save_fn: simulation_points.csv # final point
  trajectory_points_save_fn: trajectory_points.csv # all points
  variant_points_save_fn: variant_points.csv
  final_encoders_save_fn: final_encoders.pt # final encoders
  similar_encoders_save_fn: similar_encoders.pt # most similar optimal encoders

  # Plots
  complexity_accuracy_plot_fn: complexity_accuracy.png
  complexity_distortion_plot_fn: complexity_distortion.png
  complexity_mse_plot_fn: complexity_mse.png

  encoder_tile_plots_dir: encoder_tile_plots # tile plots per run
  encoder_line_plots_dir: encoder_line_plots 
  encoders_faceted_lines_plot_fn: encoders_faceted_lines.png # for all runs
  encoders_faceted_tiles_plot_fn: encoders_faceted_tiles.png

  # Hydra automatic folder naming

  # holds curve points
  curve_subdir: states=${game.num_states}/signals=${game.num_signals}/prior=${game.prior_init_alpha}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_gamma}

  # for plots etc. that summarize simulation sweeps
  sim_sweep_subdir:  ${filepaths.curve_subdir}/dynamics=${simulation.dynamics.name}/ii=${simulation.dynamics.imprecise_imitation_gamma}/population_size=${simulation.dynamics.population_size}/num_runs=${simulation.num_runs}/seed=${seed} # note that population size is null in RD

  # where the points corresponding to a single simulation will be saved
  simulation_subdir: ${filepaths.sim_sweep_subdir}/discr_need=${game.discriminative_need_gamma} # note both discr need and ii will be swept

  # where the current working directory will be when hydra is running
  leaf_subdir: ${filepaths.simulation_subdir}

  # hydra run root directory
  hydra_run_root: outputs

  # hydra multirun root directory
  hydra_sweep_root: multirun

hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.num_states
          - game.num_signals
          - simulation.dynamics.population_size
          - simulation.dynamics.imprecise_imitation_gamma
          - game.prior_init_alpha
          - game.distance
          - game.meaning_dist_gamma
          - game.discriminative_need_gamma
          - simulation.dynamics.name
          - simulation.num_runs
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python run_simulations.py -m simulation.dynamics.imprecise_imitation_gamma=2