# MAIN (ROOT) CONFIG FILE
defaults:
  - game: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  


seed: 42

# Paths of files used for consuming and producing data
filepaths: 
  # TODO: refactor naming for ib, ub
  # experiment outputs
  curve_points_save_fn: curve_points.csv # I[M:W], I[W:U]
  ub_curve_points_save_fn: ub_curve_points.csv # I[M:W], MSE
  simulation_points_save_fn: simulation_points.csv # final point, for all trials
  ub_points_save_fn: ub_points.csv # final point, for all trials
  trajectory_points_save_fn: trajectory_points.csv # all points, for all trials
  variant_points_save_fn: variant_points.csv
  tradeoff_plot_fn: tradeoff.png
  ub_plot_fn: ub.png

  # hydra automatic folder naming
  game_subdir: states=${game.num_states}/signals=${game.num_signals}/prior=${game.prior_init_beta}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_beta}
  # typical params to sweep for basic analysis
  common_sweep_subdir: discr_need=${game.discriminative_need_beta}/seed=${seed}
  simulation_subdir: dynamics=${simulation.dynamics.name}/num_trials=${simulation.num_trials}/population_size=${simulation.dynamics.population_size}
  leaf_subdir: ${filepaths.game_subdir}/${filepaths.common_sweep_subdir}/${filepaths.simulation_subdir}

hydra:
  run:
    dir: outputs/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.num_states
          - game.num_signals
          - simulation.dynamics.population_size
          - game.prior_init_beta
          - game.distance
          - game.meaning_dist_beta
          - game.discriminative_need_beta
          - simulation.dynamics.name
          - simulation.num_trials
          - seed

  sweep:
    dir: multirun
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python run_simulations.py -m game.similarity.param=range(1,10, 2)