# MAIN (ROOT) CONFIG FILE
defaults:
  - game: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  


seed: 42

# Paths of files used for consuming and producing data
filepaths: 

  # Curves
  curve_points_save_fn: curve_points.csv # (I[M:W], I[W:U], E[D_KL[M || M']])
  mse_curve_points_save_fn: mse_curve_points.csv # (I[M:W], E[(u - u)^2])

  # Simulation
  simulation_points_save_fn: simulation_points.csv # final point, for all trials
  trajectory_points_save_fn: trajectory_points.csv # all points, for all trials
  variant_points_save_fn: variant_points.csv

  # Plots
  complexity_accuracy_plot_fn: complexity_accuracy.png
  complexity_distortion_plot_fn: complexity_distortion.png
  complexity_mse_plot_fn: complexity_mse.png

  # hydra automatic folder naming

  # holds curve points
  curve_subdir: states=${game.num_states}/signals=${game.num_signals}/prior=${game.prior_init_beta}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_beta}

  # string to replace when saving a curve that is agnostic to simulation sweeps
  common_sweeps: discr_need=${game.discriminative_need_beta}/seed=${seed}

  simulation_subdir: dynamics=${simulation.dynamics.name}/num_trials=${simulation.num_trials}/population_size=${simulation.dynamics.population_size}

  # where the points corresponding to a single simulation will be saved
  leaf_subdir: ${filepaths.curve_subdir}/${filepaths.common_sweeps}/${filepaths.simulation_subdir}


  # hydra run root directory
  hydra_run_root: outputs

  # hydra multirun root directory
  hydra_sweep_root: multirun

hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.num_states
          - game.num_signals
          - simulation.dynamics.population_size
          - game.prior_init_beta
          - game.distance
          - game.meaning_dist_beta
          - game.discriminative_need_beta
          - simulation.dynamics.name
          - simulation.num_trials
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python run_simulations.py -m game.similarity.param=range(1,10, 2)