##############################################################################
# MAIN CONFIG FILE (for running simulations)
##############################################################################

defaults:
  - game: basic
  - simulation: basic
  - filepaths: default
  - plotting: default
  - _self_ # stuff below can override stuff above  
  # - override hydra/launcher: joblib # parallelism  

seed: 42


##############################################################################
# Hydra run and sweep configs
##############################################################################
hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.num_states
          - game.num_signals
          - simulation.dynamics.population_size
          - simulation.dynamics.imprecise_imitation_alpha
          - simulation.dynamics.population_init_tau
          - game.distance
          - game.meaning_dist_pi
          - game.discriminative_need_gamma
          - simulation.dynamics.name
          - simulation.num_runs
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python run_simulations.py -m simulation.dynamics.imprecise_imitation_gamma=2