# MAIN (ROOT) CONFIG FILE
defaults:
  - game: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  


seed: 42

# Paths of files used for consuming and producing data
filepaths: 
  # experiment outputs
  curve_points_save_fn: curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  tradeoff_plot_fn: tradeoff.png
  
  # hydra automatic folder naming
  game_subdir: states=${game.num_states}/words=${game.num_signals}/prior=${game.prior}/dist=${game.distance}/discr=${game.discriminative_need}/
  simulation_subdir: dynamics=${simulation.dynamics.name}/num_trials=${simulation.num_trials}/num_agents=${game.num_agents}
  leaf_subdir: ${filepaths.game_subdir}/${filepaths.simulation_subdir}

hydra:
  run:
    dir: outputs/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.num_states
          - game.num_signals
          - game.num_agents
          - game.prior
          - game.distance
          - game.discriminative_need
          - simulation.dynamics.name
          - simulation.num_trials

  sweep:
    dir: multirun
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python run_simulations.py -m game.similarity.param=range(1,10, 2)