hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - game.meaning_dist_pi=0.5
    - simulation/dynamics=imprecise_conditional_imitation
    - simulation.dynamics.imprecise_imitation_alpha=0.5
    - game.discriminative_need_gamma=5e-3,5e-2,5e-1,5e0,5e1,5e2
    - game.universe=100
    - game.num_signals=100
    - simulation.dynamics.population_init_tau=null
    - seed=range(8)
    - simulation.dynamics.max_its=20
    - simulation.dynamics.threshold=1e-4
    - simulation.multiprocessing=False
  job:
    name: measure
    chdir: true
    override_dirname: game.universe=100,simulation.dynamics.max_its=20,simulation.dynamics.threshold=1e-4,simulation.multiprocessing=False,simulation/dynamics=imprecise_conditional_imitation
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - filepaths.leaf_subdir
        - game.num_states
        - game.num_signals
        - simulation.dynamics.population_size
        - simulation.dynamics.imprecise_imitation_alpha
        - simulation.dynamics.population_init_tau
        - game.distance
        - game.meaning_dist_pi
        - game.discriminative_need_gamma
        - simulation.dynamics.name
        - simulation.num_runs
        - seed
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/nathanielimel/uci/projects/ibsg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/uci/projects/ibsg/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      plotting: default
      filepaths: default
      simulation: basic
      simulation/dynamics: imprecise_conditional_imitation
      game: basic
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
game:
  universe: 100
  prior: 1.0e-08
  num_signals: 100
  distance: squared_dist
  discriminative_need_gamma: 0.5
  meaning_dist_pi: 0.5
  num_processes: 6
  overwrite_curves: false
  dev_betas: false
simulation:
  dynamics:
    max_its: 20
    threshold: 0.0001
    population_init_tau: null
    imprecise_imitation_alpha: 0.5
    population_size: null
    graph: null
    name: imprecise_conditional_imitation
  num_runs: 1
  plot_all_encoders: true
  trajectory: true
  variants: false
  num_variants: 100
  multiprocessing: false
  num_processes: null
  approximate_encoders: false
  num_approximation_samples: 20
  inspect_eps: true
  inspect_eps_encoder: 1
filepaths:
  universe_fn: data/universe/${game.universe}.csv
  prior_fn: data/prior/${game.prior}.csv
  game_fn: game.pkl
  curve_points_save_fn: curve_points.csv
  mse_curve_points_save_fn: mse_curve_points.csv
  optimal_encoders_save_fn: optimal_encoders.npy
  betas_save_fn: betas.npy
  curve_metadata_save_fn: curve_config.yaml
  simulation_points_save_fn: simulation_points.csv
  trajectory_points_save_fn: trajectory_points.csv
  trajectory_encoders_save_fn: trajectory_encoders.npz
  steps_recorded_save_fn: steps_recorded.npz
  variant_points_save_fn: variant_points.csv
  final_encoders_save_fn: final_encoders.npy
  nearest_optimal_points_save_fn: nearest_optimal_points.csv
  nearest_optimal_save_fn: nearest_optimal_encoders.npy
  approximated_encoders_save_fn: approximated_encoders.npy
  approximated_simulation_points_save_fn: approximated_simulation_points.csv
  complexity_accuracy_plot_fn: complexity_accuracy.png
  complexity_distortion_plot_fn: complexity_distortion.png
  complexity_mse_plot_fn: complexity_mse.png
  efficiency_plot_fn: efficiency.png
  approximated_complexity_accuracy_plot_fn: approximated_complexity_accuracy.png
  approximated_complexity_distortion_plot_fn: approximated_complexity_distortion.png
  approximated_complexity_mse_plot_fn: approximated_complexity_mse.png
  single_eps_inspect_plot_fn: eps_encoder_idx.png
  encoder_tile_plots_dir: encoder_tile_plots
  encoder_line_plots_dir: encoder_line_plots
  encoders_faceted_lines_plot_fn: encoders_faceted_lines.png
  encoders_faceted_tiles_plot_fn: encoders_faceted_tiles.png
  approximated_encoders_faceted_lines_plot_fn: approximated_encoders_faceted_lines.png
  approximated_encoders_faceted_tiles_plot_fn: approximated_encoders_faceted_tiles.png
  nearest_optimal_faceted_lines_plot_fn: nearest_optimal_faceted_lines.png
  nearest_optimal_faceted_tiles_plot_fn: nearest_optimal_faceted_tiles.png
  trajectory_movies_dir: movies
  encoder_tile_movie_fn: tiles.mp4
  encoder_line_movie_fn: lines.mp4
  curve_subdir: universe=${game.universe}/num_signals=${game.num_signals}/prior=${game.prior}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_pi}
  simulation_subdir: ${filepaths.curve_subdir}/dynamics=${simulation.dynamics.name}/ii=${simulation.dynamics.imprecise_imitation_alpha}/discr_need=${game.discriminative_need_gamma}/population_init=${simulation.dynamics.population_init_tau}/population_size=${simulation.dynamics.population_size}/max_its=${simulation.dynamics.max_its}/num_runs=${simulation.num_runs}/seed=${seed}
  leaf_subdir: ${filepaths.simulation_subdir}
  hydra_run_root: outputs
  hydra_sweep_root: multirun
plotting:
  generate_movie_plots: false
  generate_movies: false
seed: 42
