hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - game.num_states=50
    - game.num_signals=5
    - game.meaning_dist_gamma=0
    - simulation.dynamics.imprecise_imitation_gamma=0
    - simulation/dynamics=nowak_krakauer
    - game.discriminative_need_gamma=-2,-1,1,2
  job:
    name: run_simulations
    chdir: true
    override_dirname: simulation/dynamics=nowak_krakauer
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - filepaths.leaf_subdir
        - game.num_states
        - game.num_signals
        - simulation.dynamics.population_size
        - simulation.dynamics.imprecise_imitation_gamma
        - game.prior_init_alpha
        - game.distance
        - game.meaning_dist_gamma
        - game.discriminative_need_gamma
        - simulation.dynamics.name
        - simulation.num_trials
        - seed
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/nathanielimel/uci/projects/ibsg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/uci/projects/ibsg/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      simulation: basic
      simulation/dynamics: nowak_krakauer
      game: basic
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
game:
  num_states: 50
  num_signals: 5
  distance: squared_dist
  discriminative_need_gamma: 1.0
  meaning_dist_gamma: 0
  prior_init_alpha: -8
  overwrite_curves: false
  maxbeta: 5
  minbeta: -2
  numbeta: 1500
  num_processes: null
simulation:
  dynamics:
    max_its: 200
    threshold: 1.0e-05
    population_init_minalpha: -2
    population_init_maxalpha: 5
    imprecise_imitation_gamma: 0
    population_size: 100
    graph: complete
    name: nowak_krakauer
    num_samples: 10
  use_decoder: false
  num_trials: 8
  plot_all_encoders: true
  trajectory: true
  variants: false
  multiprocessing: true
  num_processes: null
seed: 42
filepaths:
  curve_points_save_fn: curve_points.csv
  mse_curve_points_save_fn: mse_curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  trajectory_points_save_fn: trajectory_points.csv
  variant_points_save_fn: variant_points.csv
  final_encoders_save_fn: final_encoders.pt
  complexity_accuracy_plot_fn: complexity_accuracy.png
  complexity_distortion_plot_fn: complexity_distortion.png
  complexity_mse_plot_fn: complexity_mse.png
  encoder_tile_plots_dir: encoder_tile_plots
  encoder_line_plots_dir: encoder_line_plots
  encoders_faceted_lines_plot_fn: encoders_faceted_lines.png
  encoders_faceted_tiles_plot_fn: encoders_faceted_tiles.png
  curve_subdir: states=${game.num_states}/signals=${game.num_signals}/prior=${game.prior_init_alpha}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_gamma}
  sim_sweep_subdir: ${filepaths.curve_subdir}/dynamics=${simulation.dynamics.name}/ii=${simulation.dynamics.imprecise_imitation_gamma}/population_size=${simulation.dynamics.population_size}/num_trials=${simulation.num_trials}/seed=${seed}
  simulation_subdir: ${filepaths.sim_sweep_subdir}/discr_need=${game.discriminative_need_gamma}
  leaf_subdir: ${filepaths.simulation_subdir}
  hydra_run_root: outputs
  hydra_sweep_root: multirun
