hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - simulation/dynamics=imprecise_conditional_imitation
    - game.discriminative_need_gamma=range(-3,4)
    - game.universe=100
    - game.num_signals=100
  job:
    name: plot
    chdir: true
    override_dirname: game.universe=100,simulation/dynamics=imprecise_conditional_imitation
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - filepaths.leaf_subdir
        - game.num_states
        - game.num_signals
        - simulation.dynamics.population_size
        - simulation.dynamics.imprecise_imitation_gamma
        - simulation.dynamics.population_init_gamma
        - game.prior_init_alpha
        - game.distance
        - game.meaning_dist_gamma
        - game.discriminative_need_gamma
        - simulation.dynamics.name
        - simulation.num_runs
        - seed
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/nathanielimel/uci/projects/ibsg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/uci/projects/ibsg/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      filepaths: default
      simulation: basic
      simulation/dynamics: imprecise_conditional_imitation
      game: basic
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
game:
  universe: 100
  prior: -8
  num_signals: 100
  distance: squared_dist
  discriminative_need_gamma: 1.0
  meaning_dist_gamma: 0
  num_processes: 6
  overwrite_curves: false
  maxbeta: 5
  minbeta: -2
  numbeta: 1500
simulation:
  dynamics:
    max_its: 200
    threshold: 1.0e-05
    population_init_gamma: -8
    imprecise_imitation_gamma: 0
    population_size: null
    graph: null
    name: imprecise_conditional_imitation
  use_decoder: true
  num_runs: 1
  plot_all_encoders: true
  trajectory: true
  variants: false
  num_variants: 100
  multiprocessing: true
  num_processes: null
  approximate_encoders: false
  num_approximation_samples: 20
  inspect_gnid: true
  inspect_gnid_encoder: 1
filepaths:
  universe_fn: data/universe/${game.universe}.csv
  prior_fn: data/prior/${game.prior}.csv
  game_fn: game.pkl
  curve_points_save_fn: curve_points.csv
  mse_curve_points_save_fn: mse_curve_points.csv
  optimal_encoders_save_fn: optimal_encoders.npy
  betas_save_fn: betas.npy
  curve_metadata_save_fn: curve_config.yaml
  simulation_points_save_fn: simulation_points.csv
  trajectory_points_save_fn: trajectory_points.csv
  variant_points_save_fn: variant_points.csv
  final_encoders_save_fn: final_encoders.npy
  nearest_optimal_points_save_fn: nearest_optimal_points.csv
  nearest_optimal_save_fn: nearest_optimal_encoders.npy
  approximated_encoders_save_fn: approximated_encoders.npy
  approximated_simulation_points_save_fn: approximated_simulation_points.csv
  complexity_accuracy_plot_fn: complexity_accuracy.png
  complexity_distortion_plot_fn: complexity_distortion.png
  complexity_mse_plot_fn: complexity_mse.png
  efficiency_plot_fn: efficiency.png
  approximated_complexity_accuracy_plot_fn: approximated_complexity_accuracy.png
  approximated_complexity_distortion_plot_fn: approximated_complexity_distortion.png
  approximated_complexity_mse_plot_fn: approximated_complexity_mse.png
  single_gnid_inspect_plot_fn: gnid_encoder_idx.png
  encoder_tile_plots_dir: encoder_tile_plots
  encoder_line_plots_dir: encoder_line_plots
  encoders_faceted_lines_plot_fn: encoders_faceted_lines.png
  encoders_faceted_tiles_plot_fn: encoders_faceted_tiles.png
  approximated_encoders_faceted_lines_plot_fn: approximated_encoders_faceted_lines.png
  approximated_encoders_faceted_tiles_plot_fn: approximated_encoders_faceted_tiles.png
  nearest_optimal_faceted_lines_plot_fn: nearest_optimal_faceted_lines.png
  nearest_optimal_faceted_tiles_plot_fn: nearest_optimal_faceted_tiles.png
  curve_subdir: universe=${game.universe}/num_signals=${game.num_signals}/prior=${game.prior}/dist=${game.distance}/meaning_certainty=${game.meaning_dist_gamma}
  simulation_subdir: ${filepaths.curve_subdir}/dynamics=${simulation.dynamics.name}/ii=${simulation.dynamics.imprecise_imitation_gamma}/discr_need=${game.discriminative_need_gamma}/population_init=${simulation.dynamics.population_init_gamma}/population_size=${simulation.dynamics.population_size}/num_runs=${simulation.num_runs}/seed=${seed}
  leaf_subdir: ${filepaths.simulation_subdir}
  hydra_run_root: outputs
  hydra_sweep_root: multirun
seed: 42
